@host = http://localhost:3000/api

##Pruebas para empresas
GET {{host}}/empresas

###
GET {{host}}/empresas/Telcel@1

###
POST {{host}}/empresas
Content-Type: application/json

{
    "nombre": "Telcel",
    "password":"23456",
    "email": "Telcel@1"
}

###
PUT {{host}}/empresas
Content-Type: application/json

{
    "nombre": "Apple",
    "password":"23456",
    "email": "Ap@Store",
    "tipo": "Empresa",
    "ofertasEnProgreso": 0
}


###
DELETE {{host}}/empresas/Test@Empresa


