@host = http://localhost:3000/api
##Pruebas para ofertas

GET {{host}}/ofertas

###
GET {{host}}/ofertas/2

###
GET {{host}}/ofertas/Test@Empresa/Test@1
###
GET {{host}}/ofertas/dif/empresa/Amazon@1

###
GET {{host}}/ofertas/dif/usuario/RA@1

###
POST {{host}}/ofertas
Content-Type: application/json

{
    "emailUsuario":"RA@1",
    "emailEmpresa":"MercadoLibre@1",
    "salario":30000,
    "tiempoContratacion":3
}
###

PUT {{host}}/ofertas/Telcel@1/ARC@1
Content-Type: application/json

{
    "emailUsuario":"ARC@1",
    "emailEmpresa":"Telcel@1",
    "salario":3222223,
    "tiempoContratacion":3,
    "estado":"Terminada"
}
###
DELETE {{host}}/ofertas/Telcel@1/ARC@1

###
GET {{host}}/usuarios/ARC@1


###
GET {{host}}/empresas/Telcel@1

###
DELETE {{host}}/usuarios/ARC@1
###
DELETE {{host}}/empresas/Telcel@1

###
POST {{host}}/empresas
Content-Type: application/json

{
    "nombre": "Telcel",
    "password":"23456",
    "email": "Telcel@1"
}

###

POST {{host}}/usuarios/
Content-Type: application/json

{
    "nombre":"Alfonso",
    "apellido":"Ramirez",
    "email":"ARC@1",
    "password":"123"  
}
