@host = http://localhost:3000


## Pruebas para Usuarios


GET {{host}}/api/usuarios

###

GET {{host}}/api/usuarios/alfonso.4674@gmail.com

###

POST {{host}}/api/usuarios/
Content-Type: application/json

{
    "nombre":"Alfonso2",
    "apellido":"Ramirez2",
    "email":"ARCREPETIDO@1",
    "password":"123"  
}



###
PUT {{host}}/usuarios/ARCREPETIDO@1
Content-Type: application/json

{
    "nombre":"Juan",
    "apellido":"Doe",
    "tipo":"Trabajador",
    "ofertasActuales": 0,
    "estado":"Disponible",
    "password":"12345ds"  
}

###
DELETE {{host}}/usuarios/ARCREPETIDO@1
Content-Type: application/json



