@host = http://localhost:3000


## Pruebas para Usuarios


GET {{host}}/api/usuarios/admin

###

GET {{host}}/api/usuarios/Admin@1

###

POST {{host}}/api/usuarios/
Content-Type: application/json

{
    "nombre":"Administrador",
    "apellido":"PAE",
    "email":"Admin@1",
    "password":"123",
    "carrera": "Ingenieria en Sistemas",
    "aniosExperiencia": 5,
    "titulacion": "Licenciatura",
    "salarioDeseado": 25000
}



###
PUT {{host}}/api/usuarios/Admin@1
Content-Type: application/json

{   
    "tipo":"Administrador"  
}

###
DELETE {{host}}/api/usuarios/ARC@1
Content-Type: application/json



